### ISSUE TITLE
Additional fields for job model

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#53]
Nodes only have information about their memory, CPU and GPU (driver version and compute capability) available.
When querying for jobs, this information is hidden behind the docker image of a job and cannot be filtered on directly.
Therefore, when creating a new job, fill in the following fields to make filtering easy for nodes (and API calls faster):
* `cpu` (bool; obtained via docker_image -> cpu)
* `min_driver_version` (str; obtained via docker_image -> cuda_version -> min_driver_version)
* `min_compute_capability` (float; obtained via docker_image -> min_hardware_generation -> min_compute_capability)

**Comment by csterling** [comment]
@fracpete I've been researching into how to add "view" fields to models (i.e. fields which don't add columns to the table but instead follow relationships to get their data) and unfortunately there is no consistent way to do this in Django AFAIK.

In 0cb3c27fe88316f7cd0a3051071f1d56b31de26c I've implemented relationship-following for filter expressions, so you can set the `field` value of an expression to e.g. `docker_image.cpu` to filter on the CPU flag of the related Docker image. Is this sufficient for your purposes?

**Comment by fracpete** [comment]
I was thinking of a much simpler way: just add this values in the model programmatically after retrieving them.
Does the relationship-following work arbitrary deeply nested? Like `docker_image.cuda_version.min_driver_version`?

**Comment by csterling** [comment]
Unfortunately the filtering works on the values in the database, not on the in-memory models. The only way to have the filtering work on the nested values otherwise would be to duplicate the column into the related table (e.g. add a `cpu` column to the `Job` table with identical values).

However Django provides nested look-ups, so it wasn't too difficult to add them to the filtering (and yes they are arbitrarily deep). The only down-side to this is that you can't define it in one place (on the model) and have it work for both filtering and serialisation. That's what the mythical "view" field might have been able to do, in theory.
